name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Update mod version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: "gradle.properties"
          property: "plugin_version"
          value: ${{ github.event.release.tag_name }}

      - name: Build and upload
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publishPlugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_SECRET }}